# -*- coding: utf-8 -*-
"""Copie de Sppech recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-1kwxDSFymPD45KV1ufK6_HBEjgyyxo
"""
import speech_recognition as sr
import streamlit as st

def transcribe_speech_from_file(file_path):
    # Initialize recognizer
    r = sr.Recognizer()

    # Load audio file
    with sr.AudioFile(file_path) as source:
        audio = r.record(source)  # Read the entire audio file

    try:
        # Transcribe using Google Speech Recognition
        text = r.recognize_google(audio)
        return text
    except Exception as e:
        return f"Error: {str(e)}"

def main():
    st.title("Speech Recognition App")
    uploaded_file = st.file_uploader("Upload an audio file", type=["wav", "flac", "mp3", "m4a"])
    
    if uploaded_file is not None:
        st.info("Processing uploaded audio file...")
        file_path = f"/tmp/{uploaded_file.name}"
        
        # Save uploaded file to temp directory
        with open(file_path, "wb") as f:
            f.write(uploaded_file.getbuffer())

        text = transcribe_speech_from_file(file_path)
        st.write("Transcription:", text)

if __name__ == "__main__":
    main()

