# -*- coding: utf-8 -*-
"""Copie de Sppech recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-1kwxDSFymPD45KV1ufK6_HBEjgyyxo
"""
import speech_recognition as sr
import streamlit as st

def transcribe_speech():
    # Initialize recognizer class
    r = sr.Recognizer()

    # Use the microphone as the audio source
    with sr.Microphone() as source:
        st.info("Speak now...")
        audio_text = r.listen(source)
        st.info("Transcribing...")

        try:
            # Use Google Speech Recognition
            text = r.recognize_google(audio_text)
            return text
        except Exception as e:
            return f"Error: {str(e)}"

def main():
    st.title("Speech Recognition App")
    st.write("Click the button below to start speaking:")

    if st.button("Start Recording"):
        text = transcribe_speech()
        st.write("Transcription:", text)

if __name__ == "__main__":
    main()
